#Title of Project
#Women  Clothing Review

---



#Import Library

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


#Import DataSet

In [ ]:
df=pd.read_csv('/content/Womens Clothing E-Commerce Reviews.csv')

In [ ]:
df.head()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Clothing ID              23486 non-null  int64 
 1   Age                      23486 non-null  int64 
 2   Title                    19676 non-null  object
 3   Review                   22641 non-null  object
 4   Rating                   23486 non-null  int64 
 5   Recommended IND          23486 non-null  int64 
 6   Positive Feedback Count  23486 non-null  int64 
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [ ]:
df.shape

(23486, 10)

#Missing Values

Remove missing values in Reviews Columns with no Review Text

In [ ]:
df.isna().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review                      845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df[df['Review']==""]=np.NaN

In [ ]:
df['Review'].fillna("No Review",inplace=True)

In [ ]:
df.isna().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review                        0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df['Review']

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Absolutely wonderful - silky and sexy and comfortable
1                                                                                                                                                                                                            Love this dress!  it's sooo pretty.  i happened to find it in a store, and i'm glad i did bc i never would have ordered it online bc it's petite.  i bought a petite and am 5'8".  i love the length on me- hits just a little below the knee.  would definitely be a true midi on someone who

#Define Target (y) and Feature (X)

In [ ]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended IND',
       'Positive Feedback Count', 'Division Name', 'Department Name',
       'Class Name'],
      dtype='object')

In [ ]:
X=df['Review']

In [ ]:
y=df['Rating']

In [ ]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

#Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, stratify = y, random_state=42529)


In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

#Get Feature Text Coversion to Tokens

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(lowercase=True, analyzer='word',ngram_range=(2,3),stop_words= 'english',max_features=5000)

In [ ]:
X_train = cv.fit_transform(X_train)

In [ ]:
cv.get_feature_names_out()

In [ ]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test=cv.fit_transform(X_test)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 dresses', ..., 'years old',
       'yellow color', 'yoga pants'], dtype=object)

In [ ]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#Get Model Train

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(X_train, y_train)

MultinomialNB()

#Get Model Prediction

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y.pred.shape

In [ ]:
y_pred

array([4., 5., 4., ..., 3., 4., 1.])

#Get Probability of Each Predicted Class

In [ ]:
model.predict_proba(X_test)

array([[0.01597287, 0.06247668, 0.02343906, 0.86805191, 0.03005948],
       [0.01938616, 0.03618749, 0.01366139, 0.02494917, 0.9058158 ],
       [0.12714164, 0.31224624, 0.02402702, 0.4310927 , 0.10549239],
       ...,
       [0.12935707, 0.07677888, 0.54537581, 0.10858167, 0.13990657],
       [0.01039322, 0.00244866, 0.02592397, 0.69603597, 0.26519819],
       [0.3715833 , 0.28173991, 0.19139055, 0.14724676, 0.00803948]])

#Get Model Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[  17   24   29   47  136]
 [  46   60   52   92  220]
 [  91   87  115  184  384]
 [ 156  153  193  334  687]
 [ 395  302  375  737 2130]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.07      0.04       253
         2.0       0.10      0.13      0.11       470
         3.0       0.15      0.13      0.14       861
         4.0       0.24      0.22      0.23      1523
         5.0       0.60      0.54      0.57      3939

    accuracy                           0.38      7046
   macro avg       0.22      0.22      0.22      7046
weighted avg       0.41      0.38      0.39      7046



#Recategories Ratings as poor(0) and good(1)

In [ ]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [ ]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}}, inplace=True)

In [ ]:
y=df['Rating']

In [ ]:
X=df['Review']

#Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, stratify = y, random_state=42529)


In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

#Get Feature Text Conversion to Tokens

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True, analyzer='word',ngram_range=(2, 3),stop_words= 'english',
                   max_features=5000)


In [ ]:
X_train = cv.fit_transform(X_train)
X_test=cv.fit_transform(X_test)

#Get Model Re-Train

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

#Get Model Prediction

In [ ]:
y_pred = model.predict(X_test)
y_pred.shape

(7046,)

In [ ]:
y_pred

array([1., 1., 1., ..., 1., 1., 0.])

#Get Model Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[ 443 1140]
 [1202 4261]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.27      0.28      0.27      1583
         1.0       0.79      0.78      0.78      5463

    accuracy                           0.67      7046
   macro avg       0.53      0.53      0.53      7046
weighted avg       0.67      0.67      0.67      7046

